### PR TITLE
Added math_pointing.rst from SVN

### PR DESCRIPTION
**Pull request by adriaanph**
From https://katfs.kat.ac.za/svnDS/doc/trunk/sphinx/source/specification_records/math_pointing.rst, with only minor modification to de-emphasize "Fringe Finder"

### CODE REVIEW

**Comment by adriaanph** [comment]
@ludwigschwardt please have a look at this. i think it provides newcomers with a valuable overview even though it is somewhat in need of a refresh.

**Comment by ludwigschwardt** [comment]
This looks useful! I can also add some details (like the origin of our refraction model, which is no longer lost :joy:). I'll eventually update coord_chain for katpoint 1.0, because it has had a few tweaks.

Is this integrated with the rest of the documentation?

**Comment by adriaanph** [comment]
nope, i haven't added it to the TOC

**Review by ludwigschwardt — APPROVED** [review]
OK, we can iterate on this at a later stage.

**Pull request merged**
