### PR TITLE
fix out of range issue

### PR DESCRIPTION
**Pull request by mattieudv**

### CODE REVIEW

**Comment by ludwigschwardt** [comment]
Merely commenting out those lines is not going to cut it... I’ll consider something that interacts with np.errstate so that the end user has control over it.

**Comment by mattieudv** [comment]
Sure I encourage you to find a better solution, but I need this to work on datasets I am working on now, so made my own version of katpoint.

**Comment by ludwigschwardt** [comment]
You are encouraged to make your own custom branches (that’s the beauty of git) but it doesn’t need a pull request (or even pushing) to work. Closing in anticipation of a better solution.

**Comment by mattieudv** [comment]
I made the pull request to prod you into making the fix, rather than as a way to make my own version. Should I make a Jira ticket for this then instead, or will you take this forward on your own?

Of course you must be aware that even though some target_x,y values are erroneous (due to out of range), the valid ones are not being computed either.

**Comment by ludwigschwardt** [comment]
Make a ticket 😀

Yes, I’m aware - that’s the nature of exceptions. I’m also not aware of
other datasets besides yours that hit this snag regularly. 😁

L

**Pull request closed without merging**
